name: iOS üçé

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  IOS_SIMULATOR: ${{ vars.IOS_SIMULATOR }}

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Linting
        run: just lint-ios

  test:
    name: Test & Report
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Build iOS Framework
        run: just build-ios
      - name: Boot simulator
        run: |
          UDID=$(xcrun simctl list devices available -j | jq -r ".devices[] | .[] | select(.name == \"$IOS_SIMULATOR\") | .udid" | head -1)
          xcrun simctl boot "$UDID" || true
          xcrun simctl bootstatus "$UDID" -b
      - name: Test
        run: just report-ios
      - name: Report
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./build/ios/results.xcresult
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Build iOS Framework
        run: just build-ios
      - name: Build iOS App
        run: just build-ios-native
