name: iOS ðŸŽ

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  IOS_SIMULATOR: ${{ vars.IOS_SIMULATOR }}

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Linting
        run: make lint-ios

  test:
    name: Test & Report
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Decrypt GoogleService-Info.plist (Production)
        run: |
          ./scripts/decrypt.sh ios/drappula/Firebase/Production/GoogleService-Info.plist.gpg ios/drappula/Firebase/Production/GoogleService-Info.plist ${{ secrets.FIREBASE_GPG }}
      - name: Boot simulator
        run: |
          UDID=$(xcrun simctl list devices available -j | jq -r ".devices[] | .[] | select(.name == \"$IOS_SIMULATOR\") | .udid" | head -1)
          xcrun simctl boot "$UDID" || true
          echo "SIMULATOR_UDID=$UDID" >> $GITHUB_ENV
      - name: Build iOS Framework
        run: make build-ios-simulator
      - name: Wait for simulator
        run: xcrun simctl bootstatus "$SIMULATOR_UDID" -b
      - name: Test
        run: make report-ios
      - name: Report
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./build/ios/results.xcresult
          flags: ios
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Decrypt GoogleService-Info.plist (Production)
        run: |
          ./scripts/decrypt.sh ios/drappula/Firebase/Production/GoogleService-Info.plist.gpg ios/drappula/Firebase/Production/GoogleService-Info.plist ${{ secrets.FIREBASE_GPG }}
      - name: Create Secrets.plist
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          PRIVACY_POLICY_URL: ${{ vars.PRIVACY_POLICY_URL }}
        run: scripts/create-secrets-plist.sh
      - name: Build iOS Framework
        run: make build-ios
      - name: Build iOS App
        run: make build-ios-native
